version: 2
builds:
- main: ./main.go
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/zak905/kubectl-resource-backup/main.Version={{ .Version }}
archives:
- name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'